### ISSUE TITLE
Add tests for more functionality

### ISSUE THREAD

**Issue by pyasi** [pyasi/pybuildkite#2]
This repository needs tests for each of the Buildkite API functions i.e `agents.py` or `jobs.py`.

**Comment by Navneet78** [comment]
I want to do this I will write pytest for that.

**Comment by pyasi** [comment]
Sounds great, let me know if any help is needed. Also let me know which classes you plan to test so others can join in and help as well :)

**Comment by Navneet78** [comment]
I am working on jobs

**Comment by Navneet78** [comment]
#9
