### ISSUE TITLE
Paginated results

### ISSUE THREAD

**Issue by jnewbigin** [pyasi/pybuildkite#28]
Hi, I am trying to load all our builds via
`buildkite.builds().list_all`
This returns the first 100 results (as expected)
but I can't figure out if there is a way to get the next 100 results.

**Comment by pyasi** [comment]
Hello @jnewbigin we don’t currently have pagination support but i’d love to get it added. 

I can take a look when i have time and update you. If you feel keen on contributing let me know :).

**Comment by pyasi** [comment]
Should be fixed in https://github.com/pyasi/pybuildkite/pull/29. I'll release a new package 0.0.4 along with it when it's merged!

**Comment by jnewbigin** [comment]
This looks great. I'll git it a try!
Thanks
