### ISSUE TITLE
Build Create, Update, and Delete functionality for numerous endpoints

### ISSUE THREAD

**Issue by pyasi** [pyasi/pybuildkite#3]
Pipelines, Builds, Jobs, and Agents are all currently only using GET endpoints. We need full CRUD ability, adding POST, PUT, and DELETE functionality to these to make them feature complete would be great. Doesn't have to be all in one PR.

**Comment by savithakj** [comment]
I would like to contribute.I will try to solve Create,Update and Delete Pipeline.

**Comment by pyasi** [comment]
Sounds great! Reach out if you need any help =)

**Comment by pyasi** [comment]
@savithakj I've added a POST method to the client and an example for create Build. Hopefully that helps =).

**Comment by savithakj** [comment]
@pyasi I am unable to push the changes to new branch.

```
ERROR: Permission to pyasi/pybuildkite.git denied to savithakj.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists
```

**Comment by pyasi** [comment]
@savithakj you need to fork the repository and then open a PR against this repository, see how some of the other merges from contributors have done it :)

**Comment by Navneet78** [comment]
I am working on job @pyasi
