### ISSUE TITLE
Create functionality for "Users" endpoint

### ISSUE THREAD

**Issue by pyasi** [pyasi/pybuildkite#31]
Let's add the functionality provided in the documentation for the Users endpoint [here](https://buildkite.com/docs/apis/rest-api/user)

**Comment by gunisha30** [comment]
could you please elaborate a little bit?
Thanks.

**Comment by pyasi** [comment]
Hey @gunisha30, we want to add a class called `users.py`, so that we can wrap the endpoint listed in the issue. Take a look at https://github.com/pyasi/pybuildkite/blob/master/pybuildkite/annotations.py for an example of how we might call endpoint describes by Buildkite's documentation.
