### ISSUE TITLE
Create functionality for "Teams" endpoint 

### ISSUE THREAD

**Issue by pyasi** [pyasi/pybuildkite#32]
Let's add the functionality provided in the documentation for the Teams endpoint [here](https://buildkite.com/docs/apis/rest-api/teams)

**Comment by fredunit** [comment]
@pyasi I would like to claim the issue #32 Create functionality for "Teams" endpoint.

**Comment by pyasi** [comment]
Great @fredunit let me know if you have any questions!

**Comment by fredunit** [comment]
@pyasi  how to access the page/file that you have posted?

**Comment by pyasi** [comment]
The file doesn’t exist yet. We need to make a class for Teams. The link in this issue describes the endpoint
