### ISSUE TITLE
Get builds with only one state fails

### ISSUE THREAD

**Issue by Raz-B** [pyasi/pybuildkite#33]
Due to following line the state query param looks like `passed` instead of `state=passed`

https://github.com/pyasi/pybuildkite/blob/59db85d18aed949970507b3af8f1fb30b1a18e52/pybuildkite/builds.py#L316

pls add: `state=`+

**Comment by pyasi** [comment]
Hey @Raz-B thanks for pointing this out. Would you like to contribute? if not I can fix when I have the time.

**Comment by pyasi** [comment]
@Raz-B Thanks for calling this out, I've fixes this with https://github.com/pyasi/pybuildkite/pull/34
