### ISSUE TITLE
Inverted job and build functions for list_artifacts

### ISSUE THREAD

**Issue by Sup3rGeo** [pyasi/pybuildkite#39]
I believe that the functions `list_artifacts_for_job` and `list_artifacts_for_build` are inverted:

https://github.com/pyasi/pybuildkite/blob/5662972d0294a3cfb8bb801f2396ef893fc18f9a/pybuildkite/artifacts.py#L19-L42

The `list_artifacts_for_build` should not need a `job`, only the `build`. The function that gets a `job` should be `list_artifacts_for_job`.

This is also in line with the API docs: https://buildkite.com/docs/apis/rest-api/artifacts

I would also be happy to open a PR for this one

**Comment by pyasi** [comment]
Nice find! And you're correct. Let's get this in (and release alongside your other PR for 0.0.6)
