### ISSUE TITLE
Create classes for artifacts, annotations, and emojis 

### ISSUE THREAD

**Issue by pyasi** [pyasi/pybuildkite#4]
Let's get this repo to be complete with all opened API functionality provided by Buildkite. Does not have to be a single PR.

**Comment by KristoferSoler** [comment]
Okay, on it.

**Comment by KristoferSoler** [comment]
Artifacts:  #10

**Comment by pyasi** [comment]
Left a comment on the first one that likely applies to all of them. Thanks @KristoferSoler!

**Comment by pyasi** [comment]
Oh I forgot, each of these need to be added to the `buildkite` class in order to be invoked

**Comment by KristoferSoler** [comment]
> Oh I forgot, each of these need to be added to the `buildkite` class in order to be invoked

OKay, :sunglasses: give a minute.

**Comment by KristoferSoler** [comment]
> Left a comment on the first one that likely applies to all of them. Thanks @KristoferSoler!

What did you mean?

**Comment by pyasi** [comment]
I left a comment on #10 that applies to all PRs =)

**Comment by pyasi** [comment]
So it looks like the docstrings aren't filled out. Also you'll want to pull in the recent master as you have some merge conflicts.

**Comment by KristoferSoler** [comment]
> So it looks like the docstrings aren't filled out. Also you'll want to pull in the recent master as you have some merge conflicts.

Yeah xD I face that just right now.

**Comment by KristoferSoler** [comment]
Wow, now I see you put a lot of info in docstring. I will update all my branches. :bowing_man: give me some minutes my dude.

**Comment by KristoferSoler** [comment]
List of branches done:
* Annotations :arrow_right:  #14

> I will edit this as making the changes.

**Comment by KristoferSoler** [comment]
Hey @pyasi , do you need anything more?

**Comment by pyasi** [comment]
@KristoferSoler We're all set for this issue, thanks! Tests are always welcome =)
