### ISSUE TITLE
Add support for updating pipelines

### ISSUE THREAD

**Issue by bal2ag** [pyasi/pybuildkite#54]
The API provides support for updating a pipeline via `PATCH`: https://buildkite.com/docs/apis/rest-api/pipelines#update-a-pipeline

This doesn't seem to be supported by the library yet (the base client also doesn't provide a `PATCH` method, so the only way to update a pipeline currently is using the rest API directly as far as I can tell).

**Comment by pyasi** [comment]
Yep! Nice find. I can look into this and get an update out when I have time.

**Comment by pyasi** [comment]
Addressed with #56
