### ISSUE TITLE
Create functionality for the 'meta' endpoint

### ISSUE THREAD

**Issue by pyasi** [pyasi/pybuildkite#66]
Create a new file and class to incorporate the [meta API](https://buildkite.com/docs/apis/rest-api/meta). 

- Create a new file called `meta.py`
- Create a class called Meta
- Return the Meta class from a method in  [buildkite.py](https://github.com/pyasi/pybuildkite/blob/master/pybuildkite/buildkite.py)
- Write unit tests for the new code

**Comment by aitorres** [comment]
Hello! I can work on this issue :-)

**Comment by aitorres** [comment]
By the way @pyasi, I'm trying to install the environment locally by running `pip install -r requirements.txt` on a virtual environment and I'm getting a dependency conflict:

```
ERROR: Cannot install -r requirements.txt (line 5) and urllib3==1.26.5 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested urllib3==1.26.5
    requests 2.22.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1
```

I see that `urllib3` was last updated by dependencybot a few months ago, while `requests` hasn't been updated in a while. 

Both `requests` versions 2.25.0 and 2.26.0 work properly with `urllib3==1.26.5`. Just noting this in case it should be updated in the requirements file

**Comment by pyasi** [comment]
@aitorres Thanks for letting me know! It would be great if you could include that fix in your PR :)

**Comment by aitorres** [comment]
PR submitted! I have one last question (besides any possible code review / suggestions): I was wondering if a new Github Actions check should be added to run tests with `pytest` on every push. I think I can add that to the PR if needed (or on a separate PR).
