### ISSUE TITLE
Missing parameters for pipeline creation

### ISSUE THREAD

**Issue by GMNGeoffrey** [pyasi/pybuildkite#73]
The `create_yaml_pipeline` method is missing many parameters listed at https://buildkite.com/docs/apis/rest-api/pipelines#create-a-yaml-pipeline. These all need to be added. Alternatively, I would actually recommend just accepting kwargs for all parameters that don't need any further formatting. Then the Python package can be robust to changes to the Buildkite API with minimal maintenance. This comes at the cost of a more self-documenting Python API, but given the lack of activity on this repo I think it would be better to just point to the Buildkite documentation as the source of truth.

**Comment by GMNGeoffrey** [comment]
@pyasi are you still actively maintaining this repo? It looks like there hasn't really been any activity since last fall.

**Comment by pyasi** [comment]
@GMNGeoffrey Yes, there has not been much activity lately but I am interested in continuing to maintain this. I agree that given the frequency of changes to the Buildkite API that kwargs is likely a better long term decision.

**Comment by GMNGeoffrey** [comment]
Great! I'm happy to send a patch if you can deal with releasing a new pip package :-)

**Comment by GMNGeoffrey** [comment]
Didn't mean to cast aspersions wrt "lack of activity". In my opinion minimal-maintenance things are generally much better than things where the developer pretends that they're actually going to stay on top of everything forever :-D

**Comment by pyasi** [comment]
I totally agree with you! No aspersions received =). If you'd like to submit a patch I'd be happy to accept. It will be a day or two before I'm freed up to handle the pip packaging but I will!

**Comment by mwgamble** [comment]
#82 was just merged, which goes part of the way to solving this problem.

My personal opinion is that they shouldn't be replaced by a general `kwargs` argument. One of the most important reasons to use an API client like this over using `requests.post()` directly is type-safety. I would much rather see individual options added as necessary, so that I can more easily verify my own code is doing the right thing.

**Comment by mwgamble** [comment]
(it would be great if a new release could be created that includes #82)
