### ISSUE TITLE
PyPi 1.2.2 does not match GitHub 1.2.2

### ISSUE THREAD

**Issue by fd-jonathanlinn** [pyasi/pybuildkite#91]
Related to #85, the code in the 1.2.2 PyPi release doesn't actually match the code from the 1.2.2 GitHub release.  PyPi 1.2.2 looks like it was released December 20th, whereas the GitHub release was January 13th.  Could you create a new release on PyPi _and_ GitHub (either 1.2.3 or 1.3.0) so that the codebase is aligned? 🙏

**Comment by pyasi** [comment]
Done! Thank you for pointing this out.

https://github.com/pyasi/pybuildkite/releases/tag/v1.2.3

https://pypi.org/project/pybuildkite/1.2.3/
